apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiclusterscheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiclusterscheduler
  template:
    metadata:
      labels:
        app: multiclusterscheduler
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
      serviceAccountName: rbac-mck8s
      containers:
      - image: docker.io/chuangtw/mcsv1
        name: mcs
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /root/.kube/config
          name: kube-config
        resources:
          requests:
            cpu: 1
            memory: 1024Mi
      volumes:
      - name: kube-config
        hostPath:
          path: /root/.kube/config
          type: File